// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: didebaan.proto

package didebaanpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type BuildStatus int32

const (
	BuildStatus_BUILD_STATUS_INVALID         BuildStatus = 0
	BuildStatus_BUILD_STATUS_ALREADY_STARTED BuildStatus = 1
	BuildStatus_BUILD_STATUS_FAILED          BuildStatus = 2
	BuildStatus_BUILD_STATUS_SUCCESS         BuildStatus = 3
)

var BuildStatus_name = map[int32]string{
	0: "BUILD_STATUS_INVALID",
	1: "BUILD_STATUS_ALREADY_STARTED",
	2: "BUILD_STATUS_FAILED",
	3: "BUILD_STATUS_SUCCESS",
}
var BuildStatus_value = map[string]int32{
	"BUILD_STATUS_INVALID":         0,
	"BUILD_STATUS_ALREADY_STARTED": 1,
	"BUILD_STATUS_FAILED":          2,
	"BUILD_STATUS_SUCCESS":         3,
}

func (x BuildStatus) String() string {
	return proto.EnumName(BuildStatus_name, int32(x))
}
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_didebaan_4f2d911a1ace6884, []int{0}
}

type TriggerRequest struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerRequest) Reset()         { *m = TriggerRequest{} }
func (m *TriggerRequest) String() string { return proto.CompactTextString(m) }
func (*TriggerRequest) ProtoMessage()    {}
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_didebaan_4f2d911a1ace6884, []int{0}
}
func (m *TriggerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerRequest.Unmarshal(m, b)
}
func (m *TriggerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerRequest.Marshal(b, m, deterministic)
}
func (dst *TriggerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerRequest.Merge(dst, src)
}
func (m *TriggerRequest) XXX_Size() int {
	return xxx_messageInfo_TriggerRequest.Size(m)
}
func (m *TriggerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerRequest proto.InternalMessageInfo

func (m *TriggerRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type TriggerResponse struct {
	Status               BuildStatus `protobuf:"varint,1,opt,name=status,proto3,enum=didebaan.BuildStatus" json:"status,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TriggerResponse) Reset()         { *m = TriggerResponse{} }
func (m *TriggerResponse) String() string { return proto.CompactTextString(m) }
func (*TriggerResponse) ProtoMessage()    {}
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_didebaan_4f2d911a1ace6884, []int{1}
}
func (m *TriggerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerResponse.Unmarshal(m, b)
}
func (m *TriggerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerResponse.Marshal(b, m, deterministic)
}
func (dst *TriggerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerResponse.Merge(dst, src)
}
func (m *TriggerResponse) XXX_Size() int {
	return xxx_messageInfo_TriggerResponse.Size(m)
}
func (m *TriggerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerResponse proto.InternalMessageInfo

func (m *TriggerResponse) GetStatus() BuildStatus {
	if m != nil {
		return m.Status
	}
	return BuildStatus_BUILD_STATUS_INVALID
}

func (m *TriggerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TriggerRequest)(nil), "didebaan.TriggerRequest")
	proto.RegisterType((*TriggerResponse)(nil), "didebaan.TriggerResponse")
	proto.RegisterEnum("didebaan.BuildStatus", BuildStatus_name, BuildStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TriggerClient is the client API for Trigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TriggerClient interface {
	Build(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
}

type triggerClient struct {
	cc *grpc.ClientConn
}

func NewTriggerClient(cc *grpc.ClientConn) TriggerClient {
	return &triggerClient{cc}
}

func (c *triggerClient) Build(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, "/didebaan.Trigger/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriggerServer is the server API for Trigger service.
type TriggerServer interface {
	Build(context.Context, *TriggerRequest) (*TriggerResponse, error)
}

func RegisterTriggerServer(s *grpc.Server, srv TriggerServer) {
	s.RegisterService(&_Trigger_serviceDesc, srv)
}

func _Trigger_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didebaan.Trigger/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServer).Build(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Trigger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didebaan.Trigger",
	HandlerType: (*TriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _Trigger_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "didebaan.proto",
}

func init() { proto.RegisterFile("didebaan.proto", fileDescriptor_didebaan_4f2d911a1ace6884) }

var fileDescriptor_didebaan_4f2d911a1ace6884 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4f, 0x83, 0x30,
	0x1c, 0xc5, 0x65, 0x46, 0xa6, 0x5f, 0x15, 0x49, 0xfd, 0x85, 0xc6, 0xc3, 0xb2, 0xd3, 0xa2, 0x71,
	0x87, 0x79, 0xf5, 0x52, 0x56, 0x34, 0x24, 0xc4, 0x2c, 0x2d, 0x98, 0xb8, 0xcb, 0x52, 0xa4, 0x21,
	0x24, 0x8e, 0x22, 0x85, 0x9b, 0x7f, 0xbc, 0x59, 0x05, 0x94, 0xb8, 0x5b, 0x5f, 0x3e, 0xaf, 0xdf,
	0xf6, 0xbd, 0x2f, 0x58, 0x49, 0x96, 0x88, 0x98, 0xf3, 0x7c, 0x5a, 0x94, 0xb2, 0x92, 0x68, 0xbf,
	0xd5, 0xe3, 0x09, 0x58, 0x61, 0x99, 0xa5, 0xa9, 0x28, 0xa9, 0xf8, 0xac, 0x85, 0xaa, 0xd0, 0x05,
	0x98, 0xa5, 0xe0, 0x4a, 0xe6, 0x8e, 0x31, 0x32, 0x26, 0x07, 0xb4, 0x51, 0xe3, 0x25, 0x9c, 0x74,
	0x4e, 0x55, 0xc8, 0x5c, 0x09, 0x74, 0x0f, 0xa6, 0xaa, 0x78, 0x55, 0x2b, 0x6d, 0xb5, 0x66, 0xe7,
	0xd3, 0xee, 0x1d, 0xb7, 0xce, 0x3e, 0x12, 0xa6, 0x21, 0x6d, 0x4c, 0xc8, 0x81, 0xe1, 0x5a, 0x28,
	0xc5, 0x53, 0xe1, 0x0c, 0xf4, 0xe8, 0x56, 0xde, 0x7e, 0xc1, 0xe1, 0x9f, 0x0b, 0xc8, 0x81, 0x33,
	0x37, 0xf2, 0x03, 0xb2, 0x62, 0x21, 0x0e, 0x23, 0xb6, 0xf2, 0x5f, 0x5e, 0x71, 0xe0, 0x13, 0x7b,
	0x07, 0x8d, 0xe0, 0xa6, 0x47, 0x70, 0x40, 0x3d, 0x4c, 0xde, 0x36, 0x92, 0x86, 0x1e, 0xb1, 0x0d,
	0x74, 0x09, 0xa7, 0x3d, 0xc7, 0x13, 0xf6, 0x03, 0x8f, 0xd8, 0x83, 0x7f, 0x43, 0x59, 0x34, 0x9f,
	0x7b, 0x8c, 0xd9, 0xbb, 0xb3, 0x67, 0x18, 0x36, 0xc9, 0xd0, 0x23, 0xec, 0xe9, 0x8f, 0x20, 0xe7,
	0x37, 0x4a, 0xbf, 0x9f, 0xeb, 0xab, 0x2d, 0xe4, 0xa7, 0x0f, 0xf7, 0x0e, 0x8e, 0xde, 0xe5, 0xba,
	0xe3, 0xee, 0x31, 0x69, 0x4e, 0x8b, 0x4d, 0xeb, 0x0b, 0x63, 0x09, 0x2d, 0x2a, 0xe2, 0xd8, 0xd4,
	0xab, 0x78, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x1b, 0x23, 0x66, 0x9c, 0x01, 0x00, 0x00,
}
